name: build
run-name: Tests and build project
on:
  push:
#    branches-ignore:
#      - 'main'
    paths:
      - 'annotation-processor/src/**'
      - 'core-annotations/src/**'
      - 'ddd-annotations/src/**'
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven
      - run: mvn --batch-mode package