name: deploy
run-name: Deploy to registry
on:
  push:
    branches:
      - 'main'
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+'
jobs:
  cleanup:
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package-to-remove:
          - dragee-maven-plugin
          - dragee-maven-bom
          - annotation-processor
          - core-annotations
          - ddd-annotations
    steps:
      - name: Clean packages relative to main branch
        uses: paulushcgcj/delete-github-package@1.0.0
        with:
          type: maven
          name: io.dragee.${{ matrix.package-to-remove }}
          version: 'main'
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven
      - name: Set pom version with tag name
        run: mvn versions:set -DnewVersion=${{ github.ref_name }}
      - name: Deploy to Github Package Registry
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "<settings><servers><server><id>gh</id><username>$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $1}')</username><password>\${env.GITHUB_TOKEN}</password></server></servers></settings>" > settings.xml
          DEPLOYMENT_REPOSITORY="gh::default::https://maven.pkg.github.com/${GITHUB_REPOSITORY}"
          mvn --settings settings.xml deploy -DaltDeploymentRepository="${DEPLOYMENT_REPOSITORY}"